CREATE DATABASE CPFD
GO
USE CPFD
GO
CREATE TABLE CLIENTE
(
CPF					CHAR(11)		NOT NULL,
NOME				VARCHAR(100)		NULL,
EMAIL				VARCHAR(200)		NULL,
LIMITE_DE_CREDITO	DECIMAL(7,2)		NULL,
DT_NASCIMENTO		DATE				NULL
PRIMARY KEY (CPF)
)
GO
----------------------------------------------------------------------------------------------------------------------
CREATE PROCEDURE ETP1 (@CPF CHAR(11), @I INT, @RES INT OUTPUT)
AS
	DECLARE @V1 VARCHAR(09),
			@PC INT,
			@RP1 INT,
			@RP2 INT,
			@VAL DECIMAL(38,5),
			@INC INT
	SET @INC = 10
	SET @V1 = ''
	SET @PC= 1
	SET @VAL =0
	SET @RES = 0
	--PRINT('OK')
	WHILE (@I >0)
	BEGIN
		SET @V1 = SUBSTRING(@CPF,@PC,1)
		SET @PC = @PC+1
		SET @RES = @RES + (CAST(@V1 AS INT)*(@I+1))
		--PRINT('PC -'+CAST(@V1 AS VARCHAR(50)))
		--PRINT('VAL I -'+CAST(@I AS VARCHAR(50)))
		--PRINT('VAL @RES -'+CAST(@RES AS VARCHAR(50)))
		SET @I = @I - 1
	END
	SET @RP1 = @RES/11
	SET @RP2 = @RES%11
	SET @RES = 0
	IF(@RP2  >= 2)
		BEGIN
			SET @RES = 11-@RP2
		END


GO
CREATE PROCEDURE ETP2 (@CPF CHAR(20),@TF BIT OUTPUT)
AS
	SET @TF = 1
	/*
	IF(@CPF LIKE '%-%' OR @CPF LIKE '%.%')
	BEGIN
		SET @CPF =REPLACE(REPLACE(@CPF,'.',''),'-','')
	END
	*/
	SET @CPF =REPLACE(REPLACE(@CPF,'.',''),'-','')
	PRINT(@CPF)
	IF(LEN(@CPF) != 11)
		BEGIN
			SET @TF = 0
		END
	ELSE
		BEGIN
			DECLARE @I1 INT, @RES1 INT
			SET @I1 = 9
			SET @RES1 = 0
			WHILE (@I1 <=10)
				BEGIN
				EXEC ETP1 @CPF,@I1,@RES1 OUTPUT
				--PRINT(@CPF)
				--PRINT(@RES1)
				--PRINT('IVAL B'+CAST(@I1 AS VARCHAR(20)))
				IF(@RES1 != SUBSTRING(@CPF,(@I1+1),1))
					BEGIN
						SET @TF = 0
						BREAK;
					END
				SET @I1 = @I1 + 1
				END
		END

----------------------------------------------------------------------------------------------------------------------
DECLARE @CPF1 CHAR(20), @TF2 BIT, @I1 INT, @RES1 INT
SET @CPF1 = '50267775032'
SET @TF2 = 0
SET @I1 = 9
SET @RES1 = 0

--EXEC ETP1 @CPF1,@I1,@RES1 OUTPUT
--PRINT(@RES1)

EXEC ETP2 @CPF1, @TF2 OUTPUT
PRINT @TF2



--I
INSERT INTO CLIENTE VALUES
('50267775032','BERG','BERG@GMAIL.COM',12.89,GETDATE()),
('92454845059','BOLDER','BOLD@GMAIL.COM',123.79,GETDATE()),
('88541775046','AKENHOUWER','AKEN@GMAIL.COM',09.78,GETDATE())
--D
DELETE CLIENTE WHERE CLIENTE.CPF LIKE '%92454845059%'
--A
UPDATE CLIENTE
SET CLIENTE.NOME = 'GUNNER', CLIENTE.EMAIL = 'GUNNER@GMAIL.COM', CLIENTE.LIMITE_DE_CREDITO = 98.9,
CLIENTE.DT_NASCIMENTO = GETDATE()
WHERE CLIENTE.CPF LIKE '%92454845059%'
------------------
SELECT * FROM CLIENTE
----------------------------------------------------------------------------------------------------------------------
GO
CREATE PROCEDURE OPT (@OPT VARCHAR(01),@CPFP VARCHAR(20),@NOMEP VARCHAR(100),@EMAILP VARCHAR(200),
@LIMIT DECIMAL(7,2), @NASCI DATE, @MSGR VARCHAR(100) OUTPUT)
AS
	SET @CPFP =REPLACE(REPLACE(@CPFP,'.',''),'-','')
	DECLARE @TFP BIT
	SET @TFP = 0
	EXEC ETP2 @CPFP, @TFP OUTPUT
	IF(@CPFP IS NOT NULL AND @TFP = 1)
	BEGIN
		IF(UPPER(@OPT) = 'D' AND (SELECT C.CPF FROM CLIENTE C WHERE C.CPF LIKE @CPFP) IS NOT NULL)
		BEGIN
			SET @MSGR = 'DELETANDO' 
			DELETE CLIENTE WHERE CLIENTE.CPF LIKE @CPFP
		END
		ELSE
		BEGIN
			IF(UPPER(@OPT) = 'D' AND (SELECT C.CPF FROM CLIENTE C WHERE C.CPF LIKE @CPFP) IS NULL)
				BEGIN
					SET @MSGR = 'VALOR NAO CADASTRADO' 
			END
			----------------------------------
			IF(@NOMEP IS NOT NULL OR @EMAILP IS NOT NULL OR @LIMIT IS NOT NULL OR @NASCI IS NOT NULL)
			BEGIN
				IF(UPPER(@OPT) = 'I' AND (SELECT C.CPF FROM CLIENTE C WHERE C.CPF LIKE @CPFP) IS NULL)
				BEGIN
					SET @MSGR = 'INSERINDO' 
					INSERT INTO CLIENTE VALUES
						(@CPFP,@NOMEP,@EMAILP,@LIMIT,@NASCI)
				END
				ELSE
				BEGIN
					IF(UPPER(@OPT) = 'I' AND (SELECT C.CPF FROM CLIENTE C WHERE C.CPF LIKE @CPFP) IS NOT NULL)
					BEGIN
						SET @MSGR = 'VALOR JA CADASTRADO'
					END
				END
				IF(UPPER(@OPT) = 'A' AND (SELECT C.CPF FROM CLIENTE C WHERE C.CPF LIKE @CPFP) IS NOT NULL)
				BEGIN
					SET @MSGR = 'ATUALIZANDO' 
					UPDATE CLIENTE
					SET CLIENTE.NOME = @NOMEP, CLIENTE.EMAIL = @EMAILP, CLIENTE.LIMITE_DE_CREDITO = @LIMIT,
					CLIENTE.DT_NASCIMENTO = @NASCI
					WHERE CLIENTE.CPF LIKE @CPFP
				END
				ELSE
				BEGIN
					IF(UPPER(@OPT) = 'A' AND (SELECT C.CPF FROM CLIENTE C WHERE C.CPF LIKE @CPFP) IS NULL)
					BEGIN
						SET @MSGR = 'VALOR NAO CADASTRADO'
					END
				END
			END
			ELSE
			BEGIN
				SET @MSGR = 'VALORES NULOS OU INVALIDOS'
			END
		END
	END
	ELSE
	BEGIN
		SET @MSGR = 'CPF INVALIDO' 
	END
	
DROP PROCEDURE OPT

DECLARE @OPT1 VARCHAR(01),
		@CPF1 VARCHAR(11),
		@NOME1 VARCHAR(100),
		@EMAIL1 VARCHAR(200),
		@LIMIT1 DECIMAL(7,2),
		@DTNASC DATE,
		@MSGR1 VARCHAR(100)

SET @OPT1 = 'D'
SET @CPF1 = '92454845059'
SET @NOME1 = 'BOLDER'
SET @EMAIL1 = 'BOLDER@GMAIL.COM'
SET @LIMIT1 = 123.79
SET @DTNASC = GETDATE()
SET @MSGR1 = ''

EXEC OPT @OPT1, @CPF1, @NOME1, @EMAIL1, @LIMIT1, @DTNASC, @MSGR1 OUTPUT
PRINT @MSGR1

SELECT C.CPF,C.NOME,C.EMAIL,C.LIMITE_DE_CREDITO,C.DT_NASCIMENTO FROM CLIENTE C WHERE C.CPF = '50267775032'
SELECT C.CPF,C.NOME,C.EMAIL,C.LIMITE_DE_CREDITO,C.DT_NASCIMENTO FROM CLIENTE C	